version: "3.8"

services:
    backend:
        build: ./back-end
        ports:
            - "5000:5000"

    frontend:
        build: ./front-end
        ports:
            - "3000:3000"
